version: 2

sources:

    - name: dbgen
      schema: db
      tags: ["dbgen"]      
      loader: S3
      description: "External tables"

      tables:

        - name: customer
          description: "Customers source in S3 bucket"
          identifier: src_customer

        - name: lineorder
          identifier: src_lineorder

        - name: part
          identifier: src_part

        - name: supplier
          identifier: src_supplier